// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk0HItQp6Uy4Lg2CAPzONB6WJBKo35dBo',
    appId: '1:1041428914616:web:e6d4047501871566c5ef4d',
    messagingSenderId: '1041428914616',
    projectId: 'indicaidev',
    authDomain: 'indicaidev.firebaseapp.com',
    storageBucket: 'indicaidev.appspot.com',
    measurementId: 'G-VZZSLJ4BMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8g_qHfWVavPQZSRgCYlyF83lHOWd0wC4',
    appId: '1:1041428914616:android:581eb233654f5574c5ef4d',
    messagingSenderId: '1041428914616',
    projectId: 'indicaidev',
    storageBucket: 'indicaidev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy8QgZooialFHwVc1FGap4KX3MeYa4w0o',
    appId: '1:1041428914616:ios:5452b295a156eb66c5ef4d',
    messagingSenderId: '1041428914616',
    projectId: 'indicaidev',
    storageBucket: 'indicaidev.appspot.com',
    iosClientId: '1041428914616-t40k4qua6o3a6n81cpa6c8rfseov67o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.indikai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy8QgZooialFHwVc1FGap4KX3MeYa4w0o',
    appId: '1:1041428914616:ios:5452b295a156eb66c5ef4d',
    messagingSenderId: '1041428914616',
    projectId: 'indicaidev',
    storageBucket: 'indicaidev.appspot.com',
    iosClientId: '1041428914616-t40k4qua6o3a6n81cpa6c8rfseov67o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.indikai',
  );
}
